name: ci

on:
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v4

      - name: Install project
        run: npm ci

      - name: Lint
        run: npm run lint
